#!/usr/bin/env python3
"""Real local Git fixtures for the native-to-Bazel source boundary."""

import copy
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest
from unittest import mock

import source_workspace


class SourceWorkspaceTest(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name).resolve()
        self.native = self.root / "native"
        self.bazel = self.root / "bazel"
        self.native.mkdir()
        self.initialize(self.native)
        self.component = self.native / "src/swss"
        self.component.mkdir(parents=True)
        self.initialize(self.component)
        (self.component / "Cargo.lock").write_text("committed dependency revision\n")
        (self.component / ".gitignore").write_text("target/\n")
        self.commit(self.component)
        self.child = self.component / "vendor/dependency"
        self.child.mkdir(parents=True)
        self.initialize(self.child)
        (self.child / "library.h").write_text("/* recorded source */\n")
        self.commit(self.child)
        self.git(self.component, "update-index", "--add", "--cacheinfo",
                 "160000," + self.head(self.child) + ",vendor/dependency")
        self.git(self.component, "commit", "-qm", "record nested dependency")
        (self.native / ".gitignore").write_text("user.bazelrc\ntarget/\n")
        (self.native / "MODULE.bazel").write_text("module(name = 'fixture')\n")
        self.git(self.native, "add", ".gitignore", "MODULE.bazel")
        self.git(self.native, "update-index", "--add", "--cacheinfo",
                 "160000," + self.head(self.component) + ",src/swss")
        self.git(self.native, "commit", "-qm", "record component")
        self.expected = {"source_commit": self.head(self.native), "components": {
            path: {"commit": self.head(repository), "gitlink": self.head(repository)}
            for path, repository in (("src/swss", self.component),
                                     ("src/swss/vendor/dependency", self.child))},
            "source_clean": True}

    def git(self, directory, *arguments):
        environment = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
        environment.update(GIT_CONFIG_NOSYSTEM="1", GIT_CONFIG_GLOBAL=os.devnull,
                           GIT_AUTHOR_NAME="Source boundary fixture", GIT_COMMITTER_NAME="Source boundary fixture",
                           GIT_AUTHOR_EMAIL="securely1g@gmail.com", GIT_COMMITTER_EMAIL="securely1g@gmail.com")
        return subprocess.check_output(["git", "-c", "safe.directory=" + str(directory),
                                        "-C", str(directory), *arguments],
                                       env=environment, stderr=subprocess.PIPE, text=True).strip()

    def initialize(self, directory):
        self.git(directory, "init", "-q")
        self.git(directory, "remote", "add", "origin", "https://github.com/example/source-fixture.git")

    def commit(self, directory):
        self.git(directory, "add", ".")
        self.git(directory, "commit", "-qm", "fixture source")

    def head(self, directory):
        return self.git(directory, "rev-parse", "HEAD")

    def clone(self):
        return source_workspace.clone(self.native, self.bazel, self.expected)

    def test_native_lock_header_and_ignored_settings_never_enter_bazel(self):
        receipt = self.clone()
        lock = self.component / "Cargo.lock"
        lock.write_text("native Cargo resolved a local dependency\n")
        header = self.component / "generated.h"
        header.write_text("sensitive generated bytes\n")
        settings = self.native / "user.bazelrc"
        settings.write_text("build --define=native_only=true\n")
        audit = source_workspace.audit(self.native, self.expected)
        self.assertFalse(audit["clean"])
        changes = {entry["path"]: entry for entry in audit["repositories"]["src/swss"]["changes"]}
        self.assertEqual(changes["Cargo.lock"]["worktree_status"], "M")
        self.assertEqual(changes["generated.h"]["index_status"], "?")
        self.assertEqual(audit["repositories"]["."]["ignored"][0]["path"], "user.bazelrc")
        self.assertNotIn("sensitive generated bytes", json.dumps(audit))
        self.assertNotIn("native_only", json.dumps(audit))
        self.assertTrue(source_workspace.verify(self.bazel, self.expected)["clean"])
        self.assertEqual((self.bazel / "src/swss/Cargo.lock").read_text(), "committed dependency revision\n")
        self.assertFalse((self.bazel / "src/swss/generated.h").exists())
        self.assertFalse((self.bazel / "user.bazelrc").exists())
        self.assertEqual(lock.read_text(), "native Cargo resolved a local dependency\n")
        self.assertEqual(header.read_text(), "sensitive generated bytes\n")
        self.assertEqual(settings.read_text(), "build --define=native_only=true\n")
        self.assertEqual(receipt["verification"]["components"], self.expected["components"])

    def test_clones_all_nested_repositories_with_independent_objects_and_public_origins(self):
        receipt = self.clone()
        self.assertEqual(set(receipt["repositories"]), {".", *self.expected["components"]})
        for path, repository in receipt["repositories"].items():
            native = self.native if path == "." else self.native / path
            cloned = self.bazel if path == "." else self.bazel / path
            self.assertEqual(self.head(native), self.head(cloned))
            self.assertEqual(self.git(cloned, "remote", "get-url", "origin"), repository["origin"])
            self.assertTrue((cloned / ".git").is_dir())
            self.assertFalse((cloned / ".git/objects/info/alternates").exists())
            for source in (native / ".git/objects").rglob("*"):
                if not source.is_file():
                    continue
                target = cloned / ".git/objects" / source.relative_to(native / ".git/objects")
                self.assertTrue(target.is_file())
                self.assertNotEqual((source.stat().st_dev, source.stat().st_ino),
                                    (target.stat().st_dev, target.stat().st_ino))
                self.assertEqual(target.stat().st_nlink, 1)

    def test_source_ignored_artifacts_are_not_copied(self):
        (self.native / "target").mkdir()
        (self.native / "target/old-artifact").write_text("not source\n")
        self.clone()
        self.assertFalse((self.bazel / "target").exists())

    def test_initialized_submodules_with_git_files_get_independent_clones(self):
        for name, repository in (("swss", self.component), ("nested", self.child)):
            metadata = self.native / ".git/modules" / name
            metadata.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(repository / ".git", metadata)
            (repository / ".git").write_text("gitdir: " + str(metadata) + "\n")
            self.git(repository, "config", "core.worktree", str(repository))
        self.clone()
        for path in self.expected["components"]:
            self.assertTrue((self.native / path / ".git").is_file())
            self.assertTrue((self.bazel / path / ".git").is_dir())
            self.assertEqual(self.head(self.bazel / path), self.head(self.native / path))

    def test_verify_rejects_each_kind_of_native_contamination(self):
        self.clone()
        for name in ("src/swss/Cargo.lock", "src/swss/generated.h", "user.bazelrc"):
            path = self.bazel / name
            original = path.read_bytes() if path.exists() else None
            path.write_text("native build mutation\n")
            with self.subTest(path=name), self.assertRaisesRegex(ValueError, "modified, untracked, or ignored"):
                source_workspace.verify(self.bazel, self.expected)
            if original is None:
                path.unlink()
            else:
                path.write_bytes(original)

    def test_existing_or_symlink_destination_is_never_adopted(self):
        self.bazel.mkdir()
        marker = self.bazel / "user-work"
        marker.write_text("preserve me")
        with self.assertRaisesRegex(ValueError, "fresh"):
            self.clone()
        self.assertEqual(marker.read_text(), "preserve me")
        marker.unlink()
        self.bazel.rmdir()
        self.bazel.symlink_to(self.root / "missing")
        with self.assertRaisesRegex(ValueError, "fresh"):
            self.clone()

    def test_wrong_missing_and_omitted_revisions_fail_closed(self):
        for mutation in ("root", "child", "omitted"):
            expected = copy.deepcopy(self.expected)
            if mutation == "root":
                expected["source_commit"] = "1" * 40
            elif mutation == "child":
                expected["components"]["src/swss"] = {"commit": "2" * 40, "gitlink": "2" * 40}
            else:
                del expected["components"]["src/swss/vendor/dependency"]
            with self.subTest(mutation=mutation), self.assertRaises(ValueError):
                source_workspace.clone(self.native, self.bazel, expected)
            self.assertFalse(self.bazel.exists())

    def test_unsafe_component_paths_are_rejected_before_copy(self):
        for path in (".", "../escape", "/absolute", "src/../escape", "src//swss", "src/.git/store"):
            expected = copy.deepcopy(self.expected)
            expected["components"][path] = dict(expected["components"]["src/swss"])
            with self.subTest(path=path), self.assertRaisesRegex(ValueError, "unsafe captured component"):
                source_workspace.clone(self.native, self.bazel, expected)

    def test_nonpublic_and_credential_origins_are_not_written_to_receipts(self):
        for origin in ("https://secret-token@github.com/example/source", "http://github.com/example/source",
                       "https://127.0.0.1/source", "https://host.internal/source", str(self.root)):
            self.git(self.native, "remote", "set-url", "origin", origin)
            with self.subTest(origin=origin), self.assertRaises(ValueError) as caught:
                self.clone()
            self.assertNotIn("secret-token", str(caught.exception))
            self.assertFalse(self.bazel.exists())

    def test_native_index_and_ignored_data_are_unchanged_by_audit(self):
        (self.component / "Cargo.lock").write_text("staged native change\n")
        self.git(self.component, "add", "Cargo.lock")
        (self.component / "target").mkdir()
        (self.component / "target/result").write_text("native output")
        index = (self.component / ".git/index").read_bytes()
        result = source_workspace.audit(self.native, self.expected)
        self.assertFalse(result["clean"])
        self.assertEqual((self.component / ".git/index").read_bytes(), index)
        self.assertEqual((self.component / "target/result").read_text(), "native output")
        self.assertEqual(result["repositories"]["src/swss"]["ignored"][0]["kind"], "directory")

    def test_alternate_store_is_rejected_without_copying(self):
        alternate = self.native / ".git/objects/info/alternates"
        alternate.write_text(str(self.child / ".git/objects") + "\n")
        with self.assertRaisesRegex(ValueError, "alternate"):
            self.clone()
        self.assertFalse(self.bazel.exists())

    def test_missing_blob_never_falls_back_to_source_working_file(self):
        blob = self.git(self.native, "rev-parse", "HEAD:MODULE.bazel")
        (self.native / ".git/objects" / blob[:2] / blob[2:]).unlink()
        original = (self.native / "MODULE.bazel").read_bytes()
        with self.assertRaises(ValueError):
            self.clone()
        self.assertEqual((self.native / "MODULE.bazel").read_bytes(), original)

    def test_destination_object_links_are_rejected(self):
        self.clone()
        obj = next(path for path in (self.bazel / ".git/objects").rglob("*") if path.is_file())
        os.link(obj, self.root / "shared-object")
        with self.assertRaisesRegex(ValueError, "hardlinked"):
            source_workspace.verify(self.bazel, self.expected)

    def test_git_common_directory_cannot_redirect_clone_to_native_store(self):
        self.clone()
        (self.bazel / ".git/commondir").write_text(str(self.native / ".git") + "\n")
        with self.assertRaisesRegex(ValueError, "common directory"):
            source_workspace.verify(self.bazel, self.expected)

    def test_mixed_ownership_validation_covers_clone_and_recursive_verify(self):
        # Git's ownership test switch exercises the same safe.directory checks
        # without requiring chown/root inside the Bazel unit-test sandbox.
        original = source_workspace.subprocess.run

        def other_owner(*arguments, **kwargs):
            kwargs["env"] = dict(kwargs["env"], GIT_TEST_ASSUME_DIFFERENT_OWNER="1")
            return original(*arguments, **kwargs)

        with mock.patch.object(source_workspace.subprocess, "run", side_effect=other_owner):
            self.clone()
            self.assertTrue(source_workspace.verify(self.bazel, self.expected)["clean"])

    def test_inherited_git_configuration_cannot_redirect_source(self):
        with mock.patch.dict(os.environ, {"GIT_DIR": str(self.child / ".git"),
                                          "GIT_WORK_TREE": str(self.child),
                                          "GIT_CONFIG_COUNT": "1", "GIT_CONFIG_KEY_0": "core.worktree",
                                          "GIT_CONFIG_VALUE_0": str(self.child)}):
            receipt = self.clone()
        self.assertEqual(receipt["source_commit"], self.expected["source_commit"])

    def test_audit_reports_changed_head_and_missing_repository_without_repair(self):
        (self.child / "library.h").write_text("native changed the dependency\n")
        self.commit(self.child)
        new_head = self.head(self.child)
        audit = source_workspace.audit(self.native, self.expected)
        record = audit["repositories"]["src/swss/vendor/dependency"]
        self.assertFalse(record["head_matches"])
        self.assertEqual(record["actual_commit"], new_head)
        (self.child / ".git").rename(self.root / "retained-git")
        audit = source_workspace.audit(self.native, self.expected)
        self.assertIn("error", audit["repositories"]["src/swss/vendor/dependency"])
        self.assertTrue((self.root / "retained-git").exists())


if __name__ == "__main__":
    unittest.main()
