#!/usr/bin/env python3
"""Configure BuildBuddy caching and provide its credentials to Bazel over stdin/stdout."""

import json
import os
from pathlib import Path
import re
import stat
import sys
from urllib.parse import urlsplit


DEFAULT_ENDPOINT = "grpcs://remote.buildbuddy.io"
HELPER = "%workspace%/tools/bazel/swss/buildbuddy_cache.py"


def endpoint(environment):
    value = environment.get("BUILDBUDDY_CACHE_ENDPOINT") or DEFAULT_ENDPOINT
    match = re.fullmatch(r"grpcs://([A-Za-z0-9.-]+)(?::([0-9]+))?/?", value)
    if not match or not all(re.fullmatch(r"[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?", label)
                            for label in match[1].split(".")):
        raise ValueError("BUILDBUDDY_CACHE_ENDPOINT must be a grpcs host and optional port")
    host = match[1].lower()
    port = int(match[2] or 443)
    if not 1 <= port <= 65535:
        raise ValueError("BUILDBUDDY_CACHE_ENDPOINT has an invalid port")
    return "grpcs://" + host + (":" + str(port) if match[2] else ""), host, port


def validate_key(key):
    if not key or any(ord(character) < 33 or ord(character) > 126 for character in key):
        raise ValueError("BUILDBUDDY_API_KEY is missing or invalid")
    return key


def api_key(environment):
    path = Path(environment.get("BUILDBUDDY_API_KEY_FILE", ""))
    metadata = path.stat()
    if not stat.S_ISREG(metadata.st_mode) or metadata.st_mode & 0o777 != 0o600:
        raise ValueError("BuildBuddy credential file must have mode 0600")
    return validate_key(path.read_text())


def credentials(request, environment):
    _, host, port = endpoint(environment)
    if not isinstance(request, dict) or not isinstance(request.get("uri"), str):
        raise ValueError("Credential request must contain a URI")
    uri = urlsplit(request["uri"])
    if (uri.scheme not in ("https", "grpcs") or uri.hostname != host
            or (uri.port or 443) != port or uri.username is not None
            or uri.password is not None or uri.fragment):
        raise ValueError("Credential request does not match the configured secure cache endpoint")
    return {"headers": {"x-buildbuddy-api-key": [api_key(environment)]}}


def configuration(environment):
    address, host, _ = endpoint(environment)
    return ("# Generated by tools/bazel/swss/buildbuddy_cache.py; contains no credentials.\n"
            + "build --remote_cache=" + address + "\n"
            + "common --credential_helper=" + host + "=" + HELPER + "\n")


def configure(environment, directory):
    destination = directory / ".bazelrc.user"
    if destination.exists():
        raise ValueError("Refusing to replace an existing .bazelrc.user")
    if environment.get("BUILDBUDDY_API_KEY"):
        key = validate_key(environment["BUILDBUDDY_API_KEY"])
        settings = configuration(environment)
        key_path = Path(environment.get("BUILDBUDDY_API_KEY_FILE", "")).resolve()
        if key_path == directory.resolve() or directory.resolve() in key_path.parents:
            raise ValueError("BuildBuddy credential file must be outside the workspace")
        descriptor = os.open(key_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        try:
            with os.fdopen(descriptor, "w") as output:
                output.write(key)
            with destination.open("x") as output:
                output.write(settings)
        except BaseException:
            key_path.unlink()
            raise
        message = "BuildBuddy remote cache configured for " + endpoint(environment)[0] + "."
    else:
        message = ("BuildBuddy remote cache not configured: BUILDBUDDY_API_KEY is unavailable. "
                   "The build continues with its local caches.")
    print(message)
    if environment.get("GITHUB_STEP_SUMMARY"):
        with Path(environment["GITHUB_STEP_SUMMARY"]).open("a") as summary:
            summary.write(message + "\n")


def main():
    try:
        if sys.argv[1:] == ["get"]:
            json.dump(credentials(json.load(sys.stdin), os.environ), sys.stdout)
            sys.stdout.write("\n")
        elif sys.argv[1:] == ["configure"]:
            configure(os.environ, Path.cwd())
        else:
            raise ValueError("Expected configure or get")
    except (ValueError, OSError):
        # Bazel includes helper stderr in build logs. Never echo input or secrets.
        print("BuildBuddy cache configuration or credential request failed", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
