#!/usr/bin/env python3
"""Check the generated SWSS manifests, OCI labels and non-ASAN startup script.

Inputs are two Make-generated manifests, two Bazel-generated labels and the
startup script generated by sonic-cfggen. Script assertions protect required runtime commands as text; this suite
does not execute the startup script or boot an SWSS container."""

import json
from pathlib import Path
import sys
import unittest

INPUT_PATHS = [Path(value) for value in sys.argv[1:6]]
INIT = INPUT_PATHS[0].read_text()
RUNTIME, DEBUG = [json.loads(path.read_text()) for path in INPUT_PATHS[1:3]]
del sys.argv[1:6]


class RenderTest(unittest.TestCase):
    def test_legacy_manifest_contract(self):
        """Preserve SWSS package identity, ASIC scope, shutdown ordering and container/CLI settings."""
        manifest = RUNTIME
        self.assertEqual(manifest["package"], {"version": "1.0.0", "name": "swss", "depends": []})
        service = manifest["service"]
        self.assertEqual(service["name"], "swss")
        self.assertTrue(service["asic-service"])
        self.assertFalse(service["host-service"])
        self.assertEqual(service["warm-shutdown"], {"after": [], "before": ["syncd"]})
        self.assertEqual(service["fast-shutdown"], {"after": [], "before": ["syncd"]})
        self.assertEqual(service["syslog"], {"support-rate-limit": True})
        self.assertEqual(manifest["container"], {"privileged": False, "volumes": [], "tmpfs": []})
        self.assertEqual(manifest["cli"], {"config": "", "show": "", "clear": ""})

    def test_debug_differs_only_in_package_version(self):
        """Keep generated debug metadata identical to runtime metadata except for the version suffix."""
        runtime = RUNTIME
        debug = json.loads(json.dumps(DEBUG))
        self.assertEqual(debug["package"]["version"], "1.0.0+dbg")
        debug["package"]["version"] = runtime["package"]["version"]
        self.assertEqual(debug, runtime)

    def test_generated_manifests_and_labels_match(self):
        """Require each emitted OCI label to encode its corresponding generated manifest and version."""
        for manifest, labels, version in (
            (RUNTIME, INPUT_PATHS[3], "1.0.0"),
            (DEBUG, INPUT_PATHS[4], "1.0.0+dbg"),
        ):
            self.assertEqual(manifest["package"]["version"], version)
            key, value = labels.read_text().strip().split("=", 1)
            self.assertEqual(key, "com.azure.sonic.manifest")
            self.assertEqual(json.loads(value), manifest)

    def test_non_asan_init_retains_runtime_configuration(self):
        """Keep runtime configuration commands and shell variables after non-ASAN template rendering."""
        result = INIT
        self.assertNotIn("ENABLE_ASAN", result)
        self.assertNotIn("{%", result)
        self.assertIn('"${ASIC_VENDOR:-unknown}', result)
        self.assertIn("/etc/sonic/constants.yml", result)
        self.assertIn("sonic-cfggen $CFGGEN_PARAMS", result)
        self.assertIn("sonic-db-cli -s CONFIG_DB HGET", result)
        self.assertIn("$NAMESPACE_ID", result)
        self.assertIn("/usr/share/sonic/hwsku/hwsku-init", result)
        self.assertIn("/etc/swss/config.d/switch.json", result)
        self.assertIn("exec /usr/local/bin/supervisord", result)
        self.assertTrue(result.endswith("\n"))


if __name__ == "__main__":
    unittest.main()
