# docker image for sysmgr

DOCKER_SYSMGR_STEM = docker-sysmgr
DOCKER_SYSMGR = $(DOCKER_SYSMGR_STEM).gz
DOCKER_SYSMGR_DBG = $(DOCKER_SYSMGR_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_SYSMGR)_PATH = $(DOCKERS_PATH)/$(DOCKER_SYSMGR_STEM)
$(DOCKER_SYSMGR)_VERSION = 1.0.0
$(DOCKER_SYSMGR)_PACKAGE_NAME = sysmgr

# Register the supported native configuration with the maintained Make/Bazel
# bridge. Other architectures, ASAN and older builders retain their Make path.
ifeq ($(BLDENV),trixie)
SONIC_BAZEL_SWITCHABLE_IMAGES += $(DOCKER_SYSMGR) $(DOCKER_SYSMGR_DBG)
ifeq ($(BUILD_WITH_BAZEL_WHEN_AVAILABLE):$(CONFIGURED_ARCH),y:amd64)
ifeq ($(filter y,$(CROSS_BUILD_ENVIRON) $(MULTIARCH_QEMU_ENVIRON) $(ENABLE_ASAN)),)
SONIC_BAZEL_DOCKER_IMAGES += $(DOCKER_SYSMGR)
SONIC_BAZEL_DBG_DOCKER_IMAGES += $(DOCKER_SYSMGR_DBG)
SONIC_BAZEL_OCI_BASES += docker-config-engine-trixie.oci
docker-config-engine-trixie.oci_OCI_ARCHIVE = $(TARGET_PATH)/$(DOCKER_CONFIG_ENGINE_TRIXIE)
docker-config-engine-trixie.oci_OCI_PLATFORM = linux/amd64
$(DOCKER_SYSMGR)_BAZEL_TARGET = //dockers/docker-sysmgr:$(DOCKER_SYSMGR)
$(DOCKER_SYSMGR_DBG)_BAZEL_TARGET = //dockers/docker-sysmgr:$(DOCKER_SYSMGR_DBG)
$(DOCKER_SYSMGR)_BAZEL_DEPENDS = $(TARGET_PATH)/docker-config-engine-trixie.oci
$(DOCKER_SYSMGR_DBG)_BAZEL_DEPENDS = $($(DOCKER_SYSMGR)_BAZEL_DEPENDS)
endif
endif
endif

# Preserve legacy metadata for Make and containers that inherit these inputs.
$(DOCKER_SYSMGR)_DEPENDS += $(SYSMGR)
$(DOCKER_SYSMGR)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_TRIXIE)_DBG_DEPENDS)
$(DOCKER_SYSMGR)_DBG_DEPENDS += $(SYSMGR_DBG) $(LIBSWSSCOMMON_DBG)
$(DOCKER_SYSMGR)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_TRIXIE)_DBG_IMAGE_PACKAGES)
$(DOCKER_SYSMGR)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_TRIXIE)
$(DOCKER_SYSMGR)_LOAD_DOCKERS += $($(DOCKER_CONFIG_ENGINE_TRIXIE)_LOAD_DOCKERS)
$(DOCKER_SYSMGR_DBG)_PATH = $($(DOCKER_SYSMGR)_PATH)

SONIC_DOCKER_IMAGES += $(DOCKER_SYSMGR)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_SYSMGR)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_SYSMGR_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_SYSMGR_DBG)

$(DOCKER_SYSMGR)_CONTAINER_NAME = sysmgr
$(DOCKER_SYSMGR)_RUN_OPT += -v /var/run/dbus:/var/run/dbus:rw  
$(DOCKER_SYSMGR)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro  
$(DOCKER_SYSMGR)_GIT_REPOSITORIES += "sonic-swss"
$(DOCKER_SYSMGR)_GIT_REPOSITORIES += "sonic-swss-common"

SONIC_TRIXIE_DOCKERS += $(DOCKER_SYSMGR)
SONIC_TRIXIE_DBG_DOCKERS += $(DOCKER_SYSMGR_DBG)
