# name          lanes             alias             index       speed
Ethernet1       25,26,27,28       fortyGigE0/1      1           40000
Ethernet5       29,30,31,32       fortyGigE0/5      2           40000
